export const LOADING='LOADING'
export const LOADED='LOADED'

export const USER_LOADING='USER_LOADING'
export const USER_LOADED='USER_LOADED'
export const AUTH_ERROR='AUTH_ERROR'
export const LOGIN_SUCCESS='LOGIN_SUCCESS'
export const LOGIN_FAIL='LOGIN_FAIL'
export const LOGOUT='LOGOUT'

export const SCHOOL_LOADING='SCHOOL_LOADING'
export const SCHOOL_LOADED='SCHOOL_LOADED'
export const SCHOOL_ERROR='SCHOOL_ERROR'
export const CLASS_ADD='CLASS_ADD'
export const CLASS_REMOVE='CLASS_REMOVE'
export const CLASS_EDIT='CLASS_EDIT'

export const GROUP_ADD='GROUP_ADD'
export const GROUP_REMOVE='GROUP_REMOVE'

export const TIMETABLE_UPDATE='TIMETABLE_UPDATE'

export const STUDENT_ADD="STUDENT_ADD"
export const STUDENT_REMOVE="STUDENT_REMOVE"
export const STUDENT_UPDATE="STUDENT_UPDATE"

export const TEACHER_ADD="TEACHER_ADD"
export const TEACHER_REMOVE="TEACHER_REMOVE"
export const TEACHER_UPDATE="TEACHER_UPDATE"

export const LOADED_ROLLCALL="LOADED_ROLLCALL"
export const ADD_ROLLCALL="ADD_ROLLCALL"
export const REMOVE_ROLLCALL="REMOVE_ROLLCALL"
export const LOADING_ROLLCALL="LOADING_ROLLCALL"

export const AT_LOADING="AT_LOADING"
export const AT_LOADED="AT_LOADED"
export const AT_ADD="AT_ADD"

export const CONNECTING_SOCKET='CONNECTING_SOCKET'
export const CONNECTED_SOCKET='CONNECTED_SOCKET'
export const CONNECT_CLASS='CONNECT_CLASS'
export const DISCONNECT_CLASS='DISCONNECT_CLASS'
export const UPDATE_CLASS='UPDATE_CLASS'
export const ALL_LOCK='ALL_LOCK'
export const ALL_UNLOCK='ALL_UNLOCK'

export const LOADING_SMS='LOADING_SMS'
export const LOADED_SMS='LOADED_SMS'
export const SMS_ADD='SMS_ADD'
export const SMS_COUNT='SMS_COUNT'

export const HOMEWORK_LOADED='HOMEWORK_LOADED'
export const HOMEWORK_LOADING='HOMEWORK_LOADING'
export const HOMEWORK_ADD='HOMEWORK_ADD'
export const HOMEWORK_REMOVE='HOMEWORK_REMOVE'
export const HOMEWORK_UPDATE='HOMEWORK_UPDATE'

export const NOTIFI_LOADED='NOTIFI_LOADED'
export const NOTIFI_LOADING='NOTIFI_LOADING'
export const NOTIFI_ADD='NOTIFI_ADD'
export const NOTIFI_REMOVE='NOTIFI_REMOVE'
export const NOTIFI_UPDATE='NOTIFI_UPDATE'

export const COURSE_LOADED='COURSE_LOADED'
export const COURSE_LOADING='COURSE_LOADING'
export const COURSE_ADD='COURSE_ADD'
export const COURSE_REMOVE='COURSE_REMOVE'
export const COURSE_UPDATE='COURSE_UPDATE'