export const LOADING='LOADING'
export const LOADED='LOADED'

export const USER_LOADING='USER_LOADING'
export const USER_LOADED='USER_LOADED'
export const AUTH_ERROR='AUTH_ERROR'
export const LOGIN_SUCCESS='LOGIN_SUCCESS'
export const LOGIN_FAIL='LOGIN_FAIL'
export const LOGOUT='LOGOUT'

export const SCHOOL_LOADING='SCHOOL_LOADING'
export const SCHOOL_LOADED='SCHOOL_LOADED'
export const SCHOOL_ERROR='SCHOOL_ERROR'
export const CLASS_ADD='CLASS_ADD'

export const GROUP_ADD='GROUP_ADD'
export const GROUP_REMOVE='GROUP_REMOVE'

export const TIMETABLE_UPDATE='TIMETABLE_UPDATE'

export const STUDENT_ADD="STUDENT_ADD"
export const STUDENT_REMOVE="STUDENT_REMOVE"
export const STUDENT_UPDATE="STUDENT_UPDATE"

export const TEACHER_ADD="TEACHER_ADD"
export const TEACHER_REMOVE="TEACHER_REMOVE"
export const TEACHER_UPDATE="TEACHER_UPDATE"

export const LOADED_ROLLCALL="LOADED_ROLLCALL"
export const ADD_ROLLCALL="ADD_ROLLCALL"
export const REMOVE_ROLLCALL="REMOVE_ROLLCALL"
export const LOADING_ROLLCALL="LOADING_ROLLCALL"

export const AT_LOADING="AT_LOADING"
export const AT_LOADED="AT_LOADED"
export const AT_ADD="AT_ADD"

export const CONNECTING_SOCKET='CONNECTING_SOCKET'
export const CONNECTED_SOCKET='CONNECTED_SOCKET'
export const CONNECT_CLASS='CONNECT_CLASS'
export const DISCONNECT_CLASS='DISCONNECT_CLASS'
export const UPDATE_CLASS='UPDATE_CLASS'
export const ALL_LOCK='ALL_LOCK'
export const ALL_UNLOCK='ALL_UNLOCK'
