import {StyleSheet, Dimensions} from 'react-native'
export const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;
export const styles=StyleSheet.create({
    background:{
        width:'100%',
        height:'100%',
        padding:10
    },
    title:{
        height:50,
        width:'100%',
        flexDirection:'row',
        marginBottom:20
    },
    profileButton:{
        width:100,
        height:25,
        borderRadius:10,
        backgroundColor:'#0AD46F',
        alignItems:'center',
        justifyContent:'center'
    },
    actionButtons:{
        width:100,
        height:100,
        borderRadius:50, 
        alignItems:'center',
        justifyContent:'center'
    },
    myApps:{
        width:(windowWidth-80)/2,
        height:(windowWidth-80)/2,
        borderColor:'#1e1e1e',
        borderWidth:0.5,
        borderRadius:25,
        margin:5
    },
    showMedia:{
        width:windowWidth*0.8,
        alignItems:'center',
        justifyContent:'center'
    },
    dateTextView:{
        width:75,
        height:50,
        borderColor:'#042C5C',
        borderWidth:0.5,
        borderRadius:15,
        marginRight:10,
        alignItems:'center',
        justifyContent:'center'
    },
    alert:{
        width:windowWidth*0.8,
        maxHeight:windowHeight*0.8,
        alignItems:'center',
        justifyContent:'center'
    }
})